---
version: '3'

vars:
  GIT_ROOT:
    sh: git rev-parse --show-toplevel

includes:
  deps: .taskfiles/Taskfile_{{OS}}.yml
  chart: .taskfiles/Taskfile_chart.yml
  check: .taskfiles/Taskfile_check.yml

tasks:
  default:
    cmds:
    - task -l
    silent: true
